development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  username: username
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: username
  password: password

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: database_name_production
  pool: 5
  username: username
  password: password
